language: node_js
node_js:
- node
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod
deploy:
  provider: s3
  access_key_id:
    secure: ZCvpkUY70QPGg/PlC5ukPQYWTut4QdnCQayh/UXsWhNZPUiFTg4oE36YPKhOWtcTdt9Rc1zF3p1wnrETdaj2MjT8MJ1YvuCX1mCYSVBmYwDCq/m9E4F8PvFRBQ8zNYwF12EiHA949Pq5EFJnY8YfqSiF7eXSLoGOe1LWGKBzE0bOxZ+H3OFxoJAScLebh7AG4gFo1234dEYe1jcoumiCchwMgjSlWVEkjWR4yjVarebRGLV3+VQLJd+N92yndFOpFZTS5RIkgaVWU9YGE99V2USOr6tHc+9oLchIsg8oeBMEyo3FlvxstP3bU8L8EWChiSzaxNN6F3DOZgI5DEHmyVEQUfpOcXCM1H4mWkcfxu4BSM7Eq5swIKIzA5G3yEu4HSt3iNbVR1nQHyLHsqH9/1KUVdPZ0WXNe4cO7XE6+mDVuCoH3GSSQNnq2R8ddELGLUqfX+QoEFwnseca/XXqPMgGdqOJWPyIwufAmXdf2gXmgOnRpVfNq9h9T56R2h7opqwXDUzokY74phuNRH7UEUXKyaGYf9gkh/knb7lInl9aq+59Lcz4U095zhdJ5FrTx15JYKD5pMcYdM/5qWjxOUHVsun+RD6Bkx2WUK4UrV7HWdac0+qGR1C5u60mjkoH2H0LN/qEn0dBH9AMl/BeYOrLbdINvJ0oC+kz651xIbA=
  secret_access_key:
    secure: mSDYx4yrg5dxJeKEoVV18ydbXVpBCOKxn4nPggUwAoGp4Wlv/jHxxVqkcq5FVLkhl+5nD4o4BTht3r/Mfr9/GOvnevGgy3i4sW/7sMpG4ANep7wS3GFnn7Js8xE4uPIo2QOMJNAcwjauG5VexicwoZxxoh5x5Qus1DZezKgtg7evY4v2BsDdf7ES6zxKmmqwHlpWn4gdi9JEjTpWKmUwocZdjeCE0gqJAwEnhtZN+uwMoURyUEHpq98Ktstac0a4NCLpe/AnoEszaZ4SfTTpQMzxk7ipoKX6oaSSgBndfTs224QjnuCL2tfGNhy5We2VL4Yz9zeqRRK0gf9qdIvvBfz+D0bFUvdhbJ5WQcNMKh0HlYqUBWC1DVQUsviFbWMvJn7po+mJ6VsflALe421sUgnEyKxtt6T9xmSWUe4p9L+wczauF4aiDBO+oXNMFtNH1Ess37KGRg6nU8W0hAjFZUkjAbUqzUt1SIPyvWMFcPmz9/8Ym10/xKDrjfiplONSozaExq9lT7yyBJhbBDshoCC0GjXv5P0WWWDfbfkWEpDGy4W8sGPV3sPJNtAmfPQN/JVoFteJLj92YsDi3Q3prCHtoqddTaDlYJ4hDxq+pUmDk3klsGF8A8/1hddFIUelEKIhM9GsfqnHHQeTKFfuQlhiu1S3xwZ39/ey8WSR4Uk=
  bucket: recipes.reedmartz.com
  skip_cleanup: true
  local_dir: dist/recipes
  on:
    branch: develop
notifications:
  email:
    on_failure: change
    on_success: always
