# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 02:35
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    RecipeIngredient = apps.get_model("recipes", "RecipeIngredient")
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeThrough = Recipe.ingredients.through

    mappings = (RecipeIngredient(recipe=ri.recipe, ingredient=ri.ingredient)
                for ri in RecipeThrough.objects.all().iterator())

    RecipeIngredient.objects.bulk_create(mappings)


def reverse_func(apps, schema_editor):
    RecipeIngredient = apps.get_model("recipes", "RecipeIngredient")
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeThrough = Recipe.ingredients.through

    mappings = (RecipeThrough(recipe=ri.recipe, ingredient=ri.ingredient)
                for ri in RecipeIngredient.objects.all().iterator())

    RecipeThrough.objects.bulk_create(mappings)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredients'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
