# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_migrate_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients_new',
            new_name='ingredients'
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        )
    ]
