# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20171231_0255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([('ingredient', 'recipe')]),
        ),
    ]
