# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180107_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_trivial',
            field=models.BooleanField(default=False),
        ),
    ]
